## LSTM

In [1]:
import pandas as pd
from google.colab import drive


drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
data_APT = pd.read_csv('/content/drive/MyDrive/data_APT.csv', encoding='utf-8')
data_APT.info()
data_APT

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95104 entries, 0 to 95103
Data columns (total 19 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Building_Age                     95104 non-null  int64
 1   JS_Price                         95104 non-null  int64
 2   JS_BA                            95104 non-null  float64
 3   Population                       95104 non-null  int64
 4   UR                               95104 non-null  float64
 5   LC_index                         95104 non-null  float64
 6   CA_index                         95104 non-null  float64
 7   TC_index                         95104 non-null  float64
 8   SDT_index                        95104 non-null  float64
 9   HSP_index                        95104 non-null  float64
 10  Sell_Price                       95104 non-null  float64
 11  Crime_Rates                      95104 non-null  float64
 12  IR                               95104 non-null  float64
 13  Region_Name                      95104 non-null  float64
 14  Building_Use                     95104 non-null  float64
 15  YearMonth                        95104 non-null  float64
 16  Shortest_Distance_to_Subway      95104 non-null  float64
 17  Shortest_Distance_to_University  95104 non-null  float64
 18  Shortest_Distance_to_School      95104 non-null  float64
dtypes: float64(16), int64(3)
memory usage: 13.8 MB

,Building_Age,JS_Price,JS_BA,Population,UR,LC_index,CA_index,TC_index,SDT_index,HSP_index,Sell_Price,Crime_Rates,IR,Region_Name,Building_Use,YearMonth,Shortest_Distance_to_Subway,Shortest_Distance_to_University,Shortest_Distance_to_School
0,15,18000,59.97,299533,3.800000,72.000000,78.200000,74.200000,114.099327,81.200000,31400.00,0.930480,2.75,45044.494431,36298.957205,24751.162447,459.389192,1783.606149,370.003165
1,32,30000,84.43,557563,3.800000,72.000000,78.200000,74.200000,113.009872,81.200000,100404.17,0.842083,2.75,46291.251616,36298.957205,24751.162447,540.778887,3723.160551,336.123079
2,14,22000,59.82,368260,3.800000,72.000000,78.200000,74.200000,113.009872,81.200000,56836.67,0.836749,2.75,45647.228435,36298.957205,24751.162447,351.857009,1517.638732,470.686016
3,25,18000,47.94,494724,3.800000,72.000000,78.200000,74.200000,114.099106,81.200000,82850.00,0.943467,2.75,38158.999820,36298.957205,24751.162447,1304.834707,3053.953581,180.644334
4,12,23500,149.97,420803,3.800000,72.000000,78.200000,74.200000,114.270256,81.200000,34030.00,0.854310,2.75,28287.374586,36298.957205,24751.162447,1787.847611,718.700972,318.836190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95099,26,45000,84.20,384272,3.963951,102.715637,100.784225,100.768990,132.138962,160.718903,54000.00,0.779744,3.50,25440.160271,36298.957205,39138.034946,256.025690,1952.815142,188.219471
95100,13,40000,59.60,291384,3.963951,102.715637,100.783485,100.768990,132.138962,160.718903,107500.00,0.779744,3.50,27311.877616,36298.957205,39138.034946,605.827621,658.072434,238.994104
95101,24,45000,59.97,121441,3.963951,102.715637,100.783485,100.768990,132.138962,160.718903,125000.00,0.779744,3.50,44539.502586,36298.957205,39138.034946,256.095668,1840.603558,167.573972
95102,31,30000,58.65,566839,3.963951,102.715637,100.783485,100.768990,132.138962,160.718903,53000.00,0.779744,3.50,30605.677721,36298.957205,39138.034946,2037.958053,1701.812476,171.601187
95103,33,25000,49.50,500104,3.972986,102.765205,100.790451,100.808098,132.138962,160.709946,42000.00,0.786914,3.50,21828.535914,36298.957205,39138.034946,1104.337646,486.959608,89.435944

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
import tensorflow as tf
from tensorflow import keras
from sklearn.ensemble import RandomForestRegressor

# Load dataset from CSV file using pandas read_csv()
data = data_APT

# Prepare input features (X) and target variable (y)
X = data.drop(columns=['JS_Price'])
y = data['JS_Price']

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
# Random Forest Model (using scikit-learn)
rf_model = RandomForestRegressor(n_estimators=1000, random_state=42)
rf_model.fit(X_train.values, y_train)
y_pred_rf_model = rf_model.predict(X_test.values)

rmse_rf_model = np.sqrt(mean_squared_error(y_test, y_pred_rf_model))
mape_rf_model = np.mean(np.abs((y_test - y_pred_rf_model) / y_test)) * 100

print("Random Forest Model - RMSE:", rmse_rf_model)
print("Random Forest Model - MAPE:", mape_rf_model)

Random Forest Model - RMSE: 6830.106950119878
Random Forest Model - MAPE: 13.393450394542286

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import EarlyStopping

# Load your real estate dataset into a pandas DataFrame
# Replace 'your_data.csv' with your actual dataset file
data = data_APT

# Assuming 'features' contains the features and 'target' contains the target variable (real estate prices)
# Adjust this based on your dataset structure
features = data.drop('JS_Price', axis=1)
target = data['JS_Price']

# Split the dataset into training, validation, and testing sets
X_train, X_temp, y_train, y_temp = train_test_split(features, target, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Standardize the features (optional but often beneficial for neural networks)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Define the sequence length (number of time steps) for your LSTM
sequence_length = 10  # Adjust this based on your data and problem

# Reshape the data into sequences
def create_sequences(data, sequence_length):
    sequences = []
    for i in range(len(data) - sequence_length + 1):
        sequence = data[i:i + sequence_length]
        sequences.append(sequence)
    return np.array(sequences)

X_train_seq = create_sequences(X_train, sequence_length)
X_val_seq = create_sequences(X_val, sequence_length)
X_test_seq = create_sequences(X_test, sequence_length)

# Build the LSTM-based neural network model
model = Sequential([
    LSTM(64, activation='relu', input_shape=(sequence_length, X_train_seq.shape[2])),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Define early stopping criteria
early_stopping = EarlyStopping(monitor='val_loss', patience=10, verbose=1, restore_best_weights=True)

# Train the model with validation data and early stopping
history = model.fit(X_train_seq, y_train[sequence_length - 1:], epochs=500, batch_size=32, verbose=1,
                    validation_data=(X_val_seq, y_val[sequence_length - 1:]), callbacks=[early_stopping])

# Predict on the test set
y_pred = model.predict(X_test_seq)

# Compute evaluation metrics - RMSE, MAE, R-squared, MAPE
def compute_metrics(y_true, y_pred):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    return rmse, mae, r2, mape

rmse, mae, r2, mape = compute_metrics(y_test[sequence_length - 1:], y_pred)

print('RMSE:', rmse)
print('MAE:', mae)
print('R-Squared:', r2)
print('MAPE:', mape)

In [ ]:
# Save the trained model to a file
model.save("APT_ANN.h5")

# Print a message to confirm the model is saved
print("Model saved to disk.")

# Load the saved model
loaded_model = tf.keras.models.load_model("APT_ANN.h5")

# Define the new data you want to make predictions on as a dictionary
new_features_dict = {
    "Building_Age": ,
    "JS_BA": ,
    "Population": ,
    "UR": ,
    "LC_index": ,
    "CA_index": ,  # Add the values for the remaining features here
    "TC_index": ,
    "SDT_index": ,
    "HSP_index": ,
    "Sell_Price": ,
    "Crime_Rates": ,
    "IR": ,
    "Shortest_Distance_to_Subway": ,
    "Shortest_Distance_to_University": ,
    "Shortest_Distance_to_School":
}

# Create a DataFrame from the new data
new_data = pd.DataFrame([new_features_dict])

# Standardize the new data using the same scaler used for training
new_data = scaler.transform(new_data)

# Predict using the loaded model
predictions = loaded_model.predict(new_data)

# The 'predictions' variable now contains the model's predictions for the "JS_Price" of the new data
print('Predicted JS_Price:', predictions[0][0])