In [1]:
import pandas as pd
from google.colab import drive


drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
data_APT = pd.read_csv('/content/drive/MyDrive/Isolation_Forest_Data/data_APT.csv', encoding='utf-8')
data_officetel = pd.read_csv('/content/drive/MyDrive/Isolation_Forest_Data/data_officetel.csv', encoding='utf-8')
data_townhouse = pd.read_csv('/content/drive/MyDrive/Isolation_Forest_Data/data_townhouse.csv', encoding='utf-8')

In [4]:
columns_to_drop = ['UR', 'HSP_index', 'CA_index', 'TC_index']
data_APT = data_APT.drop(columns = columns_to_drop)
data_APT

,Floor,Building_Age,JS_BA,Population,IR,LC_index,SDT_index,Crime_Rates,latitude,longitude,...,Region_성동구,Region_성북구,Region_송파구,Region_양천구,Region_영등포구,Region_용산구,Region_은평구,Region_종로구,Region_중구,Region_중랑구
0,4.0,8,95.73,557563,2.75,75.893532,104.547226,1.386371,37.502593,127.031140,...,0,0,0,0,0,0,0,0,0,0
1,19.0,5,63.09,557563,2.75,75.893433,104.547226,1.386371,37.485309,127.034404,...,0,0,0,0,0,0,0,0,0,0
2,9.0,5,67.50,557563,2.75,75.893394,104.547226,1.386371,37.485309,127.034404,...,0,0,0,0,0,0,0,0,0,0
3,5.0,6,129.18,557563,2.75,75.893532,104.547226,1.386371,37.506861,127.028750,...,0,0,0,0,0,0,0,0,0,0
4,1.0,6,59.61,557563,2.75,75.894302,104.547226,1.386371,37.498777,127.049879,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000656,1.0,27,49.77,384272,3.50,109.782448,82.661346,1.086769,37.615262,127.091014,...,0,0,0,0,0,0,0,0,0,1
1000657,13.0,26,59.76,384272,3.50,109.783394,82.661346,1.086769,37.597149,127.081907,...,0,0,0,0,0,0,0,0,0,1
1000658,10.0,27,49.77,384272,3.50,109.782448,82.661346,1.086769,37.615262,127.091014,...,0,0,0,0,0,0,0,0,0,1
1000659,5.0,27,39.84,384272,3.50,109.782448,82.661346,1.086769,37.615262,127.091014,...,0,0,0,0,0,0,0,0,0,1
1000660,3.0,26,50.37,384272,3.50,109.783394,82.661346,1.086769,37.597149,127.081907,...,0,0,0,0,0,0,0,0,0,1

In [5]:
columns_to_drop = ['IR', 'CA_index', 'TC_index']
data_officetel = data_officetel.drop(columns = columns_to_drop)
data_officetel

,Floor,Building_Age,JS_BA,Population,UR,LC_index,SDT_index,HSP_index,Crime_Rates,latitude,...,Region_성동구,Region_성북구,Region_송파구,Region_양천구,Region_영등포구,Region_용산구,Region_은평구,Region_종로구,Region_중구,Region_중랑구
0,7.0,8,40.56,557563,3.336898,75.152115,108.864845,72.035851,1.386371,37.518459,...,0,0,0,0,0,0,0,0,0,0
1,7.0,7,35.34,557563,3.336898,75.434006,108.814003,72.714287,1.386371,37.494073,...,0,0,0,0,0,0,0,0,0,0
2,4.0,4,56.04,486546,3.333628,75.694275,109.156708,72.508171,0.947923,37.537012,...,0,0,0,0,0,0,0,0,0,0
3,10.0,7,40.55,486546,3.333628,75.587440,109.646271,72.342224,0.947923,37.539033,...,0,0,0,0,0,0,0,0,0,0
4,15.0,7,27.10,486546,3.333628,75.692596,110.260963,72.639282,0.947923,37.539415,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73223,8.0,17,30.06,365111,2.180964,106.263687,84.272804,151.519104,1.268818,37.551994,...,0,0,0,0,0,0,0,0,0,0
73224,9.0,3,18.63,279374,2.173224,107.017700,84.808533,150.890015,0.899977,37.563143,...,1,0,0,0,0,0,0,0,0,0
73225,5.0,12,39.49,657101,2.173987,103.733124,84.929161,146.993515,0.897009,37.495723,...,0,0,1,0,0,0,0,0,0,0
73226,7.0,2,29.41,376139,2.168961,106.414925,83.754585,149.904755,1.450147,37.537253,...,0,0,0,0,1,0,0,0,0,0
73227,3.0,6,28.60,376139,2.168961,107.499985,83.344902,153.137405,1.450147,37.539769,...,0,0,0,0,1,0,0,0,0,0

In [6]:

columns_to_drop = ['CA_index', 'TC_index']
data_townhouse = data_townhouse.drop(columns = columns_to_drop)
data_townhouse

,Floor,Building_Age,JS_BA,Population,IR,UR,LC_index,SDT_index,HSP_index,Crime_Rates,...,Region_성동구,Region_성북구,Region_송파구,Region_양천구,Region_영등포구,Region_용산구,Region_은평구,Region_종로구,Region_중구,Region_중랑구
0,4.0,10,64.64,557563,2.75,3.002441,75.067017,109.957306,73.161324,1.386371,...,0,0,0,0,0,0,0,0,0,0
1,4.0,1,45.63,486546,2.75,3.002953,75.048462,109.957306,73.140366,0.947923,...,0,0,0,0,0,0,0,0,0,0
2,1.0,17,49.46,486546,2.75,2.992941,75.048462,109.957306,73.140366,0.947923,...,0,0,0,0,0,0,0,0,0,0
3,5.0,1,39.23,486546,2.75,3.002953,75.048462,109.957306,73.140366,0.947923,...,0,0,0,0,0,0,0,0,0,0
4,5.0,1,41.95,486546,2.75,3.002953,75.048462,109.957306,73.140366,0.947923,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56069,4.0,3,51.72,404484,3.50,3.129286,102.687721,76.240776,121.578835,1.116515,...,0,0,0,0,0,0,0,0,0,0
56070,2.0,15,13.16,429142,3.50,3.169702,102.709267,76.247322,121.569580,0.728011,...,0,1,0,0,0,0,0,0,0,0
56071,4.0,7,29.85,438353,3.50,3.161310,102.718582,76.240776,121.569580,0.799288,...,0,0,0,1,0,0,0,0,0,0
56072,4.0,0,29.78,217288,3.50,3.270631,102.712120,76.240776,121.578651,1.418952,...,0,0,0,0,0,1,0,0,0,0
56073,5.0,8,34.79,463298,3.50,3.161310,102.714928,76.240776,121.568657,0.815561,...,0,0,0,0,0,0,1,0,0,0

In [7]:
sample_size = 100000
random_sample = data_APT.sample(n=sample_size, random_state=42)
random_sample

,Floor,Building_Age,JS_BA,Population,IR,LC_index,SDT_index,Crime_Rates,latitude,longitude,...,Region_성동구,Region_성북구,Region_송파구,Region_양천구,Region_영등포구,Region_용산구,Region_은평구,Region_종로구,Region_중구,Region_중랑구
272828,9.0,20,41.85,570666,2.50,79.400000,120.277529,0.893936,37.564973,126.842431,...,0,0,0,0,0,0,0,0,0,0
172084,20.0,14,84.91,421837,2.75,75.400000,107.748405,1.089223,37.511041,126.882952,...,0,0,0,0,0,0,0,0,0,0
445422,4.0,21,37.67,585425,1.50,85.500000,116.592129,0.905159,37.560451,126.844869,...,0,0,0,0,0,0,0,0,0,0
669543,9.0,30,44.78,402970,1.50,94.600000,98.287671,1.096956,37.496498,126.873659,...,0,0,0,0,0,0,0,0,0,0
828939,9.0,34,84.87,325050,0.50,99.600000,117.451122,0.665626,37.660882,127.026672,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433066,4.0,5,84.97,327184,1.50,85.400000,121.310376,1.272927,37.613942,127.020726,...,0,0,0,0,0,0,0,0,0,0
853955,10.0,35,84.67,662838,0.50,101.800000,125.018103,0.802759,37.491992,127.133553,...,0,0,1,0,0,0,0,0,0,0
949819,19.0,9,124.98,652993,1.75,108.400000,94.396386,0.897009,37.517437,127.103578,...,0,0,1,0,0,0,0,0,0,0
26293,15.0,8,114.75,479088,3.00,74.507782,102.608330,0.728011,37.607033,127.038366,...,0,1,0,0,0,0,0,0,0,0
770490,1.0,20,84.75,532511,1.25,98.000000,112.039216,0.772934,37.648953,127.083313,...,0,0,0,0,0,0,0,0,0,0

In [8]:
import xgboost as xgb
import pandas as pd
import numpy as np

# Load your dataset (replace 'your_dataset.csv' with the actual file path)
data_APT = random_sample

# Columns with missing values
columns_with_missing = ["IR", "Population", "LC_index", "SDT_index", "Crime_Rates"]

# Split into training and imputation sets based on missing values in the target columns
train_set = data_APT.dropna(subset=columns_with_missing)
impute_set = data_APT[data_APT[columns_with_missing].isnull().any(axis=1)]

# Separate features and target variables
X_train = train_set.drop(columns=columns_with_missing)
X_impute = impute_set.drop(columns=columns_with_missing)

# Initialize an empty dictionary to store models
models = {}

# Set parameters for XGBoost model (you can adjust these based on your requirements)
params = {
    'objective': 'reg:squarederror',
    'eval_metric': 'rmse',
    'max_depth': 6,
    'learning_rate': 0.1,
    'n_estimators': 100  # Use 'n_estimators' instead of 'num_boost_round'
}

# Train separate XGBoost models for each target column
for column in columns_with_missing:
    y_train = train_set[column]
    model = xgb.XGBRegressor(**params)
    model.fit(X_train, y_train)
    models[column] = model

# Predict missing values in the imputation set for each target column
imputed_values = pd.DataFrame()
for column in columns_with_missing:
    model = models[column]
    imputed_values[column] = model.predict(X_impute)

# Replace missing values in the original dataset with the predicted values
data_APT.loc[data_APT[columns_with_missing].isnull().any(axis=1), columns_with_missing] = imputed_values.values

# The missing values have been imputed using XGBoost
nans = data_APT.isnull().sum()
print(nans)
data_APT.info()
data_APT

Floor                              0
Building_Age                       0
JS_BA                              0
Population                         0
IR                                 0
LC_index                           0
SDT_index                          0
Crime_Rates                        0
latitude                           0
longitude                          0
Sell_Price                         0
Shortest_Distance_to_Subway        0
Shortest_Distance_to_University    0
Shortest_Distance_to_School        0
JS_Price                           0
Year                               0
Month                              0
Region_강남구                         0
Region_강동구                         0
Region_강북구                         0
Region_강서구                         0
Region_관악구                         0
Region_광진구                         0
Region_구로구                         0
Region_금천구                         0
Region_노원구                         0
Region_도봉구                         0
Region_동대문구                        0
Region_동작구                         0
Region_마포구                         0
Region_서대문구                        0
Region_서초구                         0
Region_성동구                         0
Region_성북구                         0
Region_송파구                         0
Region_양천구                         0
Region_영등포구                        0
Region_용산구                         0
Region_은평구                         0
Region_종로구                         0
Region_중구                          0
Region_중랑구                         0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 272828 to 770490
Data columns (total 42 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Floor                            100000 non-null  float64
 1   Building_Age                     100000 non-null  int64
 2   JS_BA                            100000 non-null  float64
 3   Population                       100000 non-null  float64
 4   IR                               100000 non-null  float64
 5   LC_index                         100000 non-null  float64
 6   SDT_index                        100000 non-null  float64
 7   Crime_Rates                      100000 non-null  float64
 8   latitude                         100000 non-null  float64
 9   longitude                        100000 non-null  float64
 10  Sell_Price                       100000 non-null  float64
 11  Shortest_Distance_to_Subway      100000 non-null  float64
 12  Shortest_Distance_to_University  100000 non-null  float64
 13  Shortest_Distance_to_School      100000 non-null  float64
 14  JS_Price                         100000 non-null  int64
 15  Year                             100000 non-null  int64
 16  Month                            100000 non-null  int64
 17  Region_강남구                       100000 non-null  int64
 18  Region_강동구                       100000 non-null  int64
 19  Region_강북구                       100000 non-null  int64
 20  Region_강서구                       100000 non-null  int64
 21  Region_관악구                       100000 non-null  int64
 22  Region_광진구                       100000 non-null  int64
 23  Region_구로구                       100000 non-null  int64
 24  Region_금천구                       100000 non-null  int64
 25  Region_노원구                       100000 non-null  int64
 26  Region_도봉구                       100000 non-null  int64
 27  Region_동대문구                      100000 non-null  int64
 28  Region_동작구                       100000 non-null  int64
 29  Region_마포구                       100000 non-null  int64
 30  Region_서대문구                      100000 non-null  int64
 31  Region_서초구                       100000 non-null  int64
 32  Region_성동구                       100000 non-null  int64
 33  Region_성북구                       100000 non-null  int64
 34  Region_송파구                       100000 non-null  int64
 35  Region_양천구                       100000 non-null  int64
 36  Region_영등포구                      100000 non-null  int64
 37  Region_용산구                       100000 non-null  int64
 38  Region_은평구                       100000 non-null  int64
 39  Region_종로구                       100000 non-null  int64
 40  Region_중구                        100000 non-null  int64
 41  Region_중랑구                       100000 non-null  int64
dtypes: float64(13), int64(29)
memory usage: 32.8 MB

,Floor,Building_Age,JS_BA,Population,IR,LC_index,SDT_index,Crime_Rates,latitude,longitude,...,Region_성동구,Region_성북구,Region_송파구,Region_양천구,Region_영등포구,Region_용산구,Region_은평구,Region_종로구,Region_중구,Region_중랑구
272828,9.0,20,41.85,570666.0,2.50,79.400000,120.277529,0.893936,37.564973,126.842431,...,0,0,0,0,0,0,0,0,0,0
172084,20.0,14,84.91,421837.0,2.75,75.400000,107.748405,1.089223,37.511041,126.882952,...,0,0,0,0,0,0,0,0,0,0
445422,4.0,21,37.67,585425.0,1.50,85.500000,116.592129,0.905159,37.560451,126.844869,...,0,0,0,0,0,0,0,0,0,0
669543,9.0,30,44.78,402970.0,1.50,94.600000,98.287671,1.096956,37.496498,126.873659,...,0,0,0,0,0,0,0,0,0,0
828939,9.0,34,84.87,325050.0,0.50,99.600000,117.451122,0.665626,37.660882,127.026672,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433066,4.0,5,84.97,327184.0,1.50,85.400000,121.310376,1.272927,37.613942,127.020726,...,0,0,0,0,0,0,0,0,0,0
853955,10.0,35,84.67,662838.0,0.50,101.800000,125.018103,0.802759,37.491992,127.133553,...,0,0,1,0,0,0,0,0,0,0
949819,19.0,9,124.98,652993.0,1.75,108.400000,94.396386,0.897009,37.517437,127.103578,...,0,0,1,0,0,0,0,0,0,0
26293,15.0,8,114.75,479088.0,3.00,74.507782,102.608330,0.728011,37.607033,127.038366,...,0,1,0,0,0,0,0,0,0,0
770490,1.0,20,84.75,532511.0,1.25,98.000000,112.039216,0.772934,37.648953,127.083313,...,0,0,0,0,0,0,0,0,0,0

In [12]:
import xgboost as xgb
import pandas as pd
import numpy as np

# Load your dataset (replace 'your_dataset.csv' with the actual file path)
data_APT = data_officetel

# Columns with missing values
columns_with_missing = ["Population", "LC_index", "SDT_index", "Crime_Rates"]

# Split into training and imputation sets based on missing values in the target columns
train_set = data_APT.dropna(subset=columns_with_missing)
impute_set = data_APT[data_APT[columns_with_missing].isnull().any(axis=1)]

# Separate features and target variables
X_train = train_set.drop(columns=columns_with_missing)
X_impute = impute_set.drop(columns=columns_with_missing)

# Initialize an empty dictionary to store models
models = {}

# Set parameters for XGBoost model (you can adjust these based on your requirements)
params = {
    'objective': 'reg:squarederror',
    'eval_metric': 'rmse',
    'max_depth': 6,
    'learning_rate': 0.1,
    'n_estimators': 100  # Use 'n_estimators' instead of 'num_boost_round'
}

# Train separate XGBoost models for each target column
for column in columns_with_missing:
    y_train = train_set[column]
    model = xgb.XGBRegressor(**params)
    model.fit(X_train, y_train)
    models[column] = model

# Predict missing values in the imputation set for each target column
imputed_values = pd.DataFrame()
for column in columns_with_missing:
    model = models[column]
    imputed_values[column] = model.predict(X_impute)

# Replace missing values in the original dataset with the predicted values
data_APT.loc[data_APT[columns_with_missing].isnull().any(axis=1), columns_with_missing] = imputed_values.values

# The missing values have been imputed using XGBoost
nans = data_APT.isnull().sum()
print(nans)
data_APT.info()
data_APT

Floor                              0
Building_Age                       0
JS_BA                              0
Population                         0
UR                                 0
LC_index                           0
SDT_index                          0
HSP_index                          0
Crime_Rates                        0
latitude                           0
longitude                          0
Sell_Price                         0
Shortest_Distance_to_Subway        0
Shortest_Distance_to_University    0
Shortest_Distance_to_School        0
JS_Price                           0
Year                               0
Month                              0
Region_강남구                         0
Region_강동구                         0
Region_강북구                         0
Region_강서구                         0
Region_관악구                         0
Region_광진구                         0
Region_구로구                         0
Region_금천구                         0
Region_노원구                         0
Region_도봉구                         0
Region_동대문구                        0
Region_동작구                         0
Region_마포구                         0
Region_서대문구                        0
Region_서초구                         0
Region_성동구                         0
Region_성북구                         0
Region_송파구                         0
Region_양천구                         0
Region_영등포구                        0
Region_용산구                         0
Region_은평구                         0
Region_종로구                         0
Region_중구                          0
Region_중랑구                         0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73228 entries, 0 to 73227
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Floor                            73228 non-null  float64
 1   Building_Age                     73228 non-null  int64
 2   JS_BA                            73228 non-null  float64
 3   Population                       73228 non-null  float64
 4   UR                               73228 non-null  float64
 5   LC_index                         73228 non-null  float64
 6   SDT_index                        73228 non-null  float64
 7   HSP_index                        73228 non-null  float64
 8   Crime_Rates                      73228 non-null  float64
 9   latitude                         73228 non-null  float64
 10  longitude                        73228 non-null  float64
 11  Sell_Price                       73228 non-null  float64
 12  Shortest_Distance_to_Subway      73228 non-null  float64
 13  Shortest_Distance_to_University  73228 non-null  float64
 14  Shortest_Distance_to_School      73228 non-null  float64
 15  JS_Price                         73228 non-null  int64
 16  Year                             73228 non-null  int64
 17  Month                            73228 non-null  int64
 18  Region_강남구                       73228 non-null  int64
 19  Region_강동구                       73228 non-null  int64
 20  Region_강북구                       73228 non-null  int64
 21  Region_강서구                       73228 non-null  int64
 22  Region_관악구                       73228 non-null  int64
 23  Region_광진구                       73228 non-null  int64
 24  Region_구로구                       73228 non-null  int64
 25  Region_금천구                       73228 non-null  int64
 26  Region_노원구                       73228 non-null  int64
 27  Region_도봉구                       73228 non-null  int64
 28  Region_동대문구                      73228 non-null  int64
 29  Region_동작구                       73228 non-null  int64
 30  Region_마포구                       73228 non-null  int64
 31  Region_서대문구                      73228 non-null  int64
 32  Region_서초구                       73228 non-null  int64
 33  Region_성동구                       73228 non-null  int64
 34  Region_성북구                       73228 non-null  int64
 35  Region_송파구                       73228 non-null  int64
 36  Region_양천구                       73228 non-null  int64
 37  Region_영등포구                      73228 non-null  int64
 38  Region_용산구                       73228 non-null  int64
 39  Region_은평구                       73228 non-null  int64
 40  Region_종로구                       73228 non-null  int64
 41  Region_중구                        73228 non-null  int64
 42  Region_중랑구                       73228 non-null  int64
dtypes: float64(14), int64(29)
memory usage: 24.0 MB

,Floor,Building_Age,JS_BA,Population,UR,LC_index,SDT_index,HSP_index,Crime_Rates,latitude,...,Region_성동구,Region_성북구,Region_송파구,Region_양천구,Region_영등포구,Region_용산구,Region_은평구,Region_종로구,Region_중구,Region_중랑구
0,7.0,8,40.56,557563.0,3.336898,75.152115,108.864845,72.035851,1.386371,37.518459,...,0,0,0,0,0,0,0,0,0,0
1,7.0,7,35.34,557563.0,3.336898,75.434006,108.814003,72.714287,1.386371,37.494073,...,0,0,0,0,0,0,0,0,0,0
2,4.0,4,56.04,486546.0,3.333628,75.694275,109.156708,72.508171,0.947923,37.537012,...,0,0,0,0,0,0,0,0,0,0
3,10.0,7,40.55,486546.0,3.333628,75.587440,109.646271,72.342224,0.947923,37.539033,...,0,0,0,0,0,0,0,0,0,0
4,15.0,7,27.10,486546.0,3.333628,75.692596,110.260963,72.639282,0.947923,37.539415,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73223,8.0,17,30.06,365111.0,2.180964,106.263687,84.272804,151.519104,1.268818,37.551994,...,0,0,0,0,0,0,0,0,0,0
73224,9.0,3,18.63,279374.0,2.173224,107.017700,84.808533,150.890015,0.899977,37.563143,...,1,0,0,0,0,0,0,0,0,0
73225,5.0,12,39.49,657101.0,2.173987,103.733124,84.929161,146.993515,0.897009,37.495723,...,0,0,1,0,0,0,0,0,0,0
73226,7.0,2,29.41,376139.0,2.168961,106.414925,83.754585,149.904755,1.450147,37.537253,...,0,0,0,0,1,0,0,0,0,0
73227,3.0,6,28.60,376139.0,2.168961,107.499985,83.344902,153.137405,1.450147,37.539769,...,0,0,0,0,1,0,0,0,0,0

In [14]:
import xgboost as xgb
import pandas as pd
import numpy as np

# Load your dataset (replace 'your_dataset.csv' with the actual file path)
data_APT = data_townhouse

# Columns with missing values
columns_with_missing = ['IR', "Population", "LC_index", "SDT_index", "Crime_Rates"]

# Split into training and imputation sets based on missing values in the target columns
train_set = data_APT.dropna(subset=columns_with_missing)
impute_set = data_APT[data_APT[columns_with_missing].isnull().any(axis=1)]

# Separate features and target variables
X_train = train_set.drop(columns=columns_with_missing)
X_impute = impute_set.drop(columns=columns_with_missing)

# Initialize an empty dictionary to store models
models = {}

# Set parameters for XGBoost model (you can adjust these based on your requirements)
params = {
    'objective': 'reg:squarederror',
    'eval_metric': 'rmse',
    'max_depth': 6,
    'learning_rate': 0.1,
    'n_estimators': 100  # Use 'n_estimators' instead of 'num_boost_round'
}

# Train separate XGBoost models for each target column
for column in columns_with_missing:
    y_train = train_set[column]
    model = xgb.XGBRegressor(**params)
    model.fit(X_train, y_train)
    models[column] = model

# Predict missing values in the imputation set for each target column
imputed_values = pd.DataFrame()
for column in columns_with_missing:
    model = models[column]
    imputed_values[column] = model.predict(X_impute)

# Replace missing values in the original dataset with the predicted values
data_APT.loc[data_APT[columns_with_missing].isnull().any(axis=1), columns_with_missing] = imputed_values.values

# The missing values have been imputed using XGBoost
nans = data_APT.isnull().sum()
print(nans)
data_APT.info()
data_APT

Floor                              0
Building_Age                       0
JS_BA                              0
Population                         0
IR                                 0
UR                                 0
LC_index                           0
SDT_index                          0
HSP_index                          0
Crime_Rates                        0
latitude                           0
longitude                          0
Sell_Price                         0
Shortest_Distance_to_Subway        0
Shortest_Distance_to_University    0
Shortest_Distance_to_School        0
JS_Price                           0
Year                               0
Month                              0
Region_강남구                         0
Region_강동구                         0
Region_강북구                         0
Region_강서구                         0
Region_관악구                         0
Region_광진구                         0
Region_구로구                         0
Region_금천구                         0
Region_노원구                         0
Region_도봉구                         0
Region_동대문구                        0
Region_동작구                         0
Region_마포구                         0
Region_서대문구                        0
Region_서초구                         0
Region_성동구                         0
Region_성북구                         0
Region_송파구                         0
Region_양천구                         0
Region_영등포구                        0
Region_용산구                         0
Region_은평구                         0
Region_종로구                         0
Region_중구                          0
Region_중랑구                         0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56074 entries, 0 to 56073
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Floor                            56074 non-null  float64
 1   Building_Age                     56074 non-null  int64
 2   JS_BA                            56074 non-null  float64
 3   Population                       56074 non-null  float64
 4   IR                               56074 non-null  float64
 5   UR                               56074 non-null  float64
 6   LC_index                         56074 non-null  float64
 7   SDT_index                        56074 non-null  float64
 8   HSP_index                        56074 non-null  float64
 9   Crime_Rates                      56074 non-null  float64
 10  latitude                         56074 non-null  float64
 11  longitude                        56074 non-null  float64
 12  Sell_Price                       56074 non-null  float64
 13  Shortest_Distance_to_Subway      56074 non-null  float64
 14  Shortest_Distance_to_University  56074 non-null  float64
 15  Shortest_Distance_to_School      56074 non-null  float64
 16  JS_Price                         56074 non-null  int64
 17  Year                             56074 non-null  int64
 18  Month                            56074 non-null  int64
 19  Region_강남구                       56074 non-null  int64
 20  Region_강동구                       56074 non-null  int64
 21  Region_강북구                       56074 non-null  int64
 22  Region_강서구                       56074 non-null  int64
 23  Region_관악구                       56074 non-null  int64
 24  Region_광진구                       56074 non-null  int64
 25  Region_구로구                       56074 non-null  int64
 26  Region_금천구                       56074 non-null  int64
 27  Region_노원구                       56074 non-null  int64
 28  Region_도봉구                       56074 non-null  int64
 29  Region_동대문구                      56074 non-null  int64
 30  Region_동작구                       56074 non-null  int64
 31  Region_마포구                       56074 non-null  int64
 32  Region_서대문구                      56074 non-null  int64
 33  Region_서초구                       56074 non-null  int64
 34  Region_성동구                       56074 non-null  int64
 35  Region_성북구                       56074 non-null  int64
 36  Region_송파구                       56074 non-null  int64
 37  Region_양천구                       56074 non-null  int64
 38  Region_영등포구                      56074 non-null  int64
 39  Region_용산구                       56074 non-null  int64
 40  Region_은평구                       56074 non-null  int64
 41  Region_종로구                       56074 non-null  int64
 42  Region_중구                        56074 non-null  int64
 43  Region_중랑구                       56074 non-null  int64
dtypes: float64(15), int64(29)
memory usage: 18.8 MB

,Floor,Building_Age,JS_BA,Population,IR,UR,LC_index,SDT_index,HSP_index,Crime_Rates,...,Region_성동구,Region_성북구,Region_송파구,Region_양천구,Region_영등포구,Region_용산구,Region_은평구,Region_종로구,Region_중구,Region_중랑구
0,4.0,10,64.64,557563.0,2.75,3.002441,75.067017,109.957306,73.161324,1.386371,...,0,0,0,0,0,0,0,0,0,0
1,4.0,1,45.63,486546.0,2.75,3.002953,75.048462,109.957306,73.140366,0.947923,...,0,0,0,0,0,0,0,0,0,0
2,1.0,17,49.46,486546.0,2.75,2.992941,75.048462,109.957306,73.140366,0.947923,...,0,0,0,0,0,0,0,0,0,0
3,5.0,1,39.23,486546.0,2.75,3.002953,75.048462,109.957306,73.140366,0.947923,...,0,0,0,0,0,0,0,0,0,0
4,5.0,1,41.95,486546.0,2.75,3.002953,75.048462,109.957306,73.140366,0.947923,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56069,4.0,3,51.72,404484.0,3.50,3.129286,102.687721,76.240776,121.578835,1.116515,...,0,0,0,0,0,0,0,0,0,0
56070,2.0,15,13.16,429142.0,3.50,3.169702,102.709267,76.247322,121.569580,0.728011,...,0,1,0,0,0,0,0,0,0,0
56071,4.0,7,29.85,438353.0,3.50,3.161310,102.718582,76.240776,121.569580,0.799288,...,0,0,0,1,0,0,0,0,0,0
56072,4.0,0,29.78,217288.0,3.50,3.270631,102.712120,76.240776,121.578651,1.418952,...,0,0,0,0,0,1,0,0,0,0
56073,5.0,8,34.79,463298.0,3.50,3.161310,102.714928,76.240776,121.568657,0.815561,...,0,0,0,0,0,0,1,0,0,0

In [15]:
import lightgbm as lgb
import joblib

# Train the LightGBM model as you did before
# ...

# Save the trained model to a file
model_filename = "Townhouse_model.pkl"
joblib.dump(model, model_filename)

['Townhouse_model.pkl']

In [ ]:
import lightgbm as lgb
import joblib
import pandas as pd

# Load the saved model
model_filename = "lgb_model.pkl"
model = joblib.load(model_filename)

# Load the column names if needed
column_names_filename = "column_names.pkl"
column_names = joblib.load(column_names_filename)

# Create a new DataFrame with your independent features for prediction
new_data = pd.DataFrame({
    'Feature1': [value1],
    'Feature2': [value2],
    # Add more features as needed
})

# Make predictions using the loaded model
predictions = model.predict(new_data)

# The 'predictions' variable now contains the predicted 'Sell_Price' values for the new data
print(predictions)